name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: yarn install

      - uses: actions/checkout@v4
        with:
          repository: henrycatalinismith/henrycatalinismith.github.io
          sparse-checkout: |
            wargames/index.html
          path: _root

      - run: mv _root/wargames _site/

      - run: yarn build --output _site/play

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

